kind: pipeline
type: docker
name: sv-socialtool
trigger:
  branch:
  - master
pipeline:
  deploy:
    image: appleboy/drone-ssh
    host:
      - manager01.der-taenzer.net
    username: dockeradmin
    password:
      from_secret: ssh_pass
    port: 22
    command_timeout: 5m
    script:
      - cd /home/dockeradmin/docker/deploy/svmotor-socialtool
      - gh repo pull taenzer/svmotor-socialtool
      - gh repo sync
      - docker compose up -d
